import Toolbar from '@mui/material/Toolbar';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yokubou Heya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box display="flex" flexDirection="column" height="100%">
          <Box>
            <AppBar position="static">
              <Toolbar>
                <Box flexGrow={1}>
                  <Typography variant="h6">{metadata.title}</Typography>
                </Box>
                <Button color="inherit">Login</Button>
              </Toolbar>
            </AppBar>
          </Box>
          <Box display="flex" flex={1}>
            <Box flex={1} height="100%">
              {children}
            </Box>
          </Box>
        </Box>
      </body>
    </html>
  );
}
